#!/usr/bin/awk -f

BEGIN {
    if (ARGC != 3) {
	print "time2volume: error: needs two arguments" | "cat >&2"
	exit(1)
    }
    i = 1
    while (rc = getline < ARGV[1]) {
	split($0, a, ",")
	nt[i] = a[1]
	dt[i] = a[2]
	i++
    }
    close(ARGV[1])
    getline < ARGV[2]
    j = 1
    time = 0
    cnt = 0
    for (i = 1; $i > 0; i++) {
	printf "%.16e %s\n", time, $i
	time += dt[j]
	if (cnt == nt[j] - 1) {
	    j += 1
	    cnt = 0
	}
	cnt ++
    }
}
