H = \
config.hpp\
source/auxiliar/cbuffer.hpp\
source/auxiliar/cudaUtils.hpp\
source/auxiliar/dnnUtils.hpp\
source/auxiliar/fs.hpp\
source/auxiliar/json.hpp\
source/auxiliar/jsonInterface.hpp\
source/auxiliar/kcache.hpp\
source/auxiliar/koraliJson.hpp\
source/auxiliar/kstring.hpp\
source/auxiliar/libco/libco.h\
source/auxiliar/libco/settings.h\
source/auxiliar/logger.hpp\
source/auxiliar/math.hpp\
source/auxiliar/MPIUtils.hpp\
source/auxiliar/py2json.hpp\
source/auxiliar/reactionParser.hpp\
source/auxiliar/rtnorm/new_implementation/rtnorm_constants.hpp\
source/auxiliar/rtnorm/new_implementation/rtnorm.hpp\
source/auxiliar/rtnorm/rtnorm.hpp\
source/engine.hpp\
source/korali.hpp\
source/modules/conduit/concurrent/concurrent.hpp\
source/modules/conduit/conduit.hpp\
source/modules/conduit/distributed/distributed.hpp\
source/modules/conduit/sequential/sequential.hpp\
source/modules/distribution/distribution.hpp\
source/modules/distribution/multivariate/multivariate.hpp\
source/modules/distribution/multivariate/normal/normal.hpp\
source/modules/distribution/specific/multinomial/multinomial.hpp\
source/modules/distribution/specific/specific.hpp\
source/modules/distribution/univariate/beta/beta.hpp\
source/modules/distribution/univariate/cauchy/cauchy.hpp\
source/modules/distribution/univariate/exponential/exponential.hpp\
source/modules/distribution/univariate/gamma/gamma.hpp\
source/modules/distribution/univariate/geometric/geometric.hpp\
source/modules/distribution/univariate/igamma/igamma.hpp\
source/modules/distribution/univariate/laplace/laplace.hpp\
source/modules/distribution/univariate/logNormal/logNormal.hpp\
source/modules/distribution/univariate/normal/normal.hpp\
source/modules/distribution/univariate/poisson/poisson.hpp\
source/modules/distribution/univariate/truncatedNormal/truncatedNormal.hpp\
source/modules/distribution/univariate/uniformratio/uniformratio.hpp\
source/modules/distribution/univariate/uniform/uniform.hpp\
source/modules/distribution/univariate/univariate.hpp\
source/modules/distribution/univariate/weibull/weibull.hpp\
source/modules/experiment/experiment.hpp\
source/modules/module.hpp\
source/modules/neuralNetwork/layer/activation/activation.hpp\
source/modules/neuralNetwork/layer/convolution/convolution.hpp\
source/modules/neuralNetwork/layer/deconvolution/deconvolution.hpp\
source/modules/neuralNetwork/layer/input/input.hpp\
source/modules/neuralNetwork/layer/layer.hpp\
source/modules/neuralNetwork/layer/linear/linear.hpp\
source/modules/neuralNetwork/layer/output/output.hpp\
source/modules/neuralNetwork/layer/pooling/pooling.hpp\
source/modules/neuralNetwork/layer/recurrent/gru/gru.hpp\
source/modules/neuralNetwork/layer/recurrent/lstm/lstm.hpp\
source/modules/neuralNetwork/layer/recurrent/recurrent.hpp\
source/modules/neuralNetwork/neuralNetwork.hpp\
source/modules/problem/bayesian/bayesian.hpp\
source/modules/problem/bayesian/custom/custom.hpp\
source/modules/problem/bayesian/reference/reference.hpp\
source/modules/problem/design/design.hpp\
source/modules/problem/hierarchical/hierarchical.hpp\
source/modules/problem/hierarchical/psi/psi.hpp\
source/modules/problem/hierarchical/thetaNew/thetaNew.hpp\
source/modules/problem/hierarchical/theta/theta.hpp\
source/modules/problem/integration/integration.hpp\
source/modules/problem/optimization/optimization.hpp\
source/modules/problem/problem.hpp\
source/modules/problem/propagation/propagation.hpp\
source/modules/problem/reaction/reaction.hpp\
source/modules/problem/reinforcementLearning/continuous/continuous.hpp\
source/modules/problem/reinforcementLearning/discrete/discrete.hpp\
source/modules/problem/reinforcementLearning/reinforcementLearning.hpp\
source/modules/problem/sampling/sampling.hpp\
source/modules/problem/supervisedLearning/supervisedLearning.hpp\
source/modules/solver/agent/agent.hpp\
source/modules/solver/agent/continuous/continuous.hpp\
source/modules/solver/agent/continuous/VRACER/VRACER.hpp\
source/modules/solver/agent/discrete/discrete.hpp\
source/modules/solver/agent/discrete/dVRACER/dVRACER.hpp\
source/modules/solver/deepSupervisor/deepSupervisor.hpp\
source/modules/solver/deepSupervisor/optimizers/fAdaBelief/fAdaBelief.hpp\
source/modules/solver/deepSupervisor/optimizers/fAdaGrad/fAdaGrad.hpp\
source/modules/solver/deepSupervisor/optimizers/fAdam/fAdam.hpp\
source/modules/solver/deepSupervisor/optimizers/fGradientBasedOptimizer.hpp\
source/modules/solver/deepSupervisor/optimizers/fMadGrad/fMadGrad.hpp\
source/modules/solver/designer/designer.hpp\
source/modules/solver/executor/executor.hpp\
source/modules/solver/integrator/integrator.hpp\
source/modules/solver/integrator/montecarlo/MonteCarlo.hpp\
source/modules/solver/integrator/quadrature/Quadrature.hpp\
source/modules/solver/optimizer/AdaBelief/AdaBelief.hpp\
source/modules/solver/optimizer/Adam/Adam.hpp\
source/modules/solver/optimizer/CMAES/CMAES.hpp\
source/modules/solver/optimizer/DEA/DEA.hpp\
source/modules/solver/optimizer/gridSearch/gridSearch.hpp\
source/modules/solver/optimizer/MADGRAD/MADGRAD.hpp\
source/modules/solver/optimizer/MOCMAES/MOCMAES.hpp\
source/modules/solver/optimizer/optimizer.hpp\
source/modules/solver/optimizer/Rprop/Rprop.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_base.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_euclidean_base.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_euclidean_dense.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_euclidean_diag.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_riemannian_base.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_riemannian_const_dense.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_riemannian_const_diag.hpp\
source/modules/solver/sampler/HMC/helpers/hamiltonian_riemannian_diag.hpp\
source/modules/solver/sampler/HMC/helpers/leapfrog_base.hpp\
source/modules/solver/sampler/HMC/helpers/leapfrog_explicit.hpp\
source/modules/solver/sampler/HMC/helpers/leapfrog_implicit.hpp\
source/modules/solver/sampler/HMC/helpers/tree_helper_base.hpp\
source/modules/solver/sampler/HMC/helpers/tree_helper_euclidean.hpp\
source/modules/solver/sampler/HMC/helpers/tree_helper_riemannian.hpp\
source/modules/solver/sampler/HMC/HMC.hpp\
source/modules/solver/sampler/MCMC/MCMC.hpp\
source/modules/solver/sampler/Nested/Nested.hpp\
source/modules/solver/sampler/sampler.hpp\
source/modules/solver/sampler/TMCMC/TMCMC.hpp\
source/modules/solver/solver.hpp\
source/modules/solver/SSM/SSA/SSA.hpp\
source/modules/solver/SSM/SSM.hpp\
source/modules/solver/SSM/TauLeaping/TauLeaping.hpp\
source/sample/sample.hpp\
variable/variable.hpp\
